### ISSUE TITLE
problem with changing scenes

### ISSUE THREAD

**Issue by marioboi3112** [marioboi3112/galaxy-kong-minigame-a-month-game-jam-#1]
so i was working on a game using the haxegon library and there was this bug that was bugging me for 2 straight days, does anyone know whats wrong?
here are the two files, there is a Space.hx file that calls the Credits.hx class when a function is triggered but that doesnt seem to work...
```haxe
package;

/**
 * ...
 * @author obi3112
 */
import haxegon.*;

//NOTE! THIS IS THE MENU CLASS!, idk why i called it space lol
class Space {
	//instances
	private static var Btn:Button = new Button();
	
	//Create some arrays for the starfield.
	var star_x:Array<Int>;
	var star_y:Array<Int>;
	var star_speed:Array<Int>;
	var earth_y:Int;
	var earth_x:Int;
	function init() {
		//Initalise the arrays, and put some default values in them.
		
		star_x = []; star_y = []; star_speed = [];
		earth_y = 10; earth_x = 50;
		for (i in 0 ... 50) {
			star_x.push(Random.int(0, Gfx.screenwidth));  //Random x position on screen
			star_y.push(Random.int(0, Gfx.screenheight)); //Random y position on screen
			star_speed.push(Random.int(4, 8));    //Random speed between 8/16 pixels per frame
		}
	}
	
	function update() {
		//Change scene when you click the mouse.
			
		//Starfield
		Gfx.clearscreen();
		
		for (i in 0 ... 50) {
			//Draw slow stars darker than bright stars to give a parallex effect.
			if (star_speed[i] <= 12) {
				Gfx.fillbox(star_x[i], star_y[i], 4, 4, 0x222222);
			}else {
				Gfx.fillbox(star_x[i], star_y[i], 4, 4, 0x555555);
			}
			
			//Move the star position by the speed value
			star_x[i] -= star_speed[i];
			
			if (star_x[i] < -30) {
				//If the star is off screen, move it to the right hand side.
				star_x[i] += Gfx.screenwidth + 40;
				star_y[i] = Random.int(0, Gfx.screenheight);
				star_speed[i] = Random.int(8, 16);
			}
		}
		//render our earth(planet) to screen
		Gfx.rotation(23, Gfx.CENTER, Gfx.CENTER);
		Gfx.drawimage(earth_x, earth_y, "earth");
		Text.size = 2;
		Text.display(Text.CENTER, Text.CENTER, "GALAXY KONG!", Col.GRAY);
		Text.display(Text.CENTER, Text.CENTER - 30, "PRESS X TO PLAY", Col.WHITE);	
		controls();
		credits();

	}
	var controls_text_x:Int = 60;
	var controls_text_y:Int = Gfx.screenheight - 100;
	private function controls() {
		Btn.customButton(controls_text_x, controls_text_y, 140, 40, Col.RED); //control button
		Text.display(controls_text_x + 15, controls_text_y + 10, "CONTROLS");
		//mouse clicking l ogic
		Btn.clickButton(controls_text_x, controls_text_y, 140, 40, "CONTROLS", Controls); //call the function on the controls button
	}
	
	//credits section
	var credits_x = 60+200;
	var credits_y = Gfx.screenheight - 100;
	
	private function credits() {
		Btn.customButton(credits_x, credits_y, 140, 40, Col.RED);
		Text.display(credits_x + 15, credits_y + 10, "CREDITS");
		Btn.clickButton(credits_x, credits_y, 140,40,"CREDITS", Credits);
	}
	
	
}

```

```haxe
package;

/**
 * ...
 * @author obi3112
 */
import haxegon.*;

class Credits{
    
    private function init() {
    }
    private function update() {
        Text.size = 3;
        Text.display(Text.CENTER, 0, "CREDITS");
        Text.size = 2;
        Text.display(Text.LEFT, Text.CENTER, "CODING/MUSIC/ART: obi3112 (all by me)");
    }
}
```
the aboce class is the class that needs to be called
butt for some reason
when i extend the Controls class
it works...
i am so confused

```haxe
package;

/**
 * ...
 * @author obi3112
 */
import haxegon.*;
class Controls {
    //instances
    private static var btn:Button = new Button();
    public var left = Text.LEFT;
    public var right = Text.RIGHT;
    public var center = Text.CENTER;
    public var bottom = Text.BOTTOM;
    public var top = Text.TOP;
    
    private function init() {}
    private function update() {
        Text.size = 4;
        Text.display(center, 0, "CONTROLS");
        //draw a line below the CONTROLS title
        Gfx.drawline(0, 22, Gfx.screenwidth, 22,Col.RED,0);
        
        Text.size = 2;
        Text.display(left, left + 40, "You can move the player by using the LEFT and RIGHT arrows\n to move left and right respectively,");    
    }
    
}
```
and the above one is the controls class.

**Comment by TerryCavanagh** [comment]
sorry, I don't see where the scene change is being called here!

**Comment by marioboi3112** [comment]
> sorry, I don't see where the scene change is being called here!

oh yeah sorry, i had made a separate class to handle buttons so that they would change scene, here it is!
```haxe
package;

/**
 * ...
 * @author obi3112
 */

 

import haxegon.*;
class Button 
{

	public function new() {} //empty constructor
	
	public function clickButton(x, y, w, h, str:String, scene) {
		for (i in x ... x + w) {
			for (j in y ... y + h) {
				if (Mouse.x == i && Mouse.y == j && Mouse.leftclick()) {
						trace(str);
						Scene.change(scene);
				}
			}
		}
	}
	
	public function customButton(x,y,width,height,col) {
		Gfx.drawbox(x,y,width,height,col);
	}
}
```

**Comment by TerryCavanagh** [comment]
Yeah, hmm, sorry - that looks to me like it should work 🤷‍♂️

What happens if you hardcode the scene change in the click button function, instead of passing it as an argument?

**Comment by marioboi3112** [comment]
then in that case it would only change to one scene and not others right? cause if i pass it as an argument, i can insert any Scene i want and it would change to that, but im gonna try it anyways...

**Comment by marioboi3112** [comment]
so i tried it but since it changes it's scene into Controls its gonna change the scene to Controls every time you click on it (on every single button), but it seems to work, but this is definitely inefficient

**Comment by TerryCavanagh** [comment]
Sure, but that indicates what the problem is!

I think you can work around this by just making Controls be a static class. Instead of "public function update", use "public static function update".

**Comment by marioboi3112** [comment]
Ok i will try it btw let me show you what the error would look like before, it would say sth like Class\<Credits\> should be Class\<Controls\>

**Comment by marioboi3112** [comment]
here is the error i got
![image](https://github.com/marioboi3112/galaxy-kong-minigame-a-month-game-jam-/assets/98112470/e4313c47-1bd2-457d-8fed-3448ed9feb80)

space.hx line 71:-
![image](https://github.com/marioboi3112/galaxy-kong-minigame-a-month-game-jam-/assets/98112470/3dd95e0f-da62-403a-8f12-bd7022cf7d1b)
controls.hx line 29:-
![image](https://github.com/marioboi3112/galaxy-kong-minigame-a-month-game-jam-/assets/98112470/badc7f52-7a1a-4148-821b-2f869d051a1f)

**Comment by TerryCavanagh** [comment]
Oh, maybe the problem is simpler than I think? Try using the type Dynamic instead of Class, see if that works.

**Comment by marioboi3112** [comment]
> Oh, maybe the problem is simpler than I think? Try using the type Dynamic instead of Class, see if that works.

are you referring to the scene argument, cause in that case it has no type, so should i just add it or are you referring to something else?

**Comment by TerryCavanagh** [comment]
> here is the error i got ![image](https://private-user-images.githubusercontent.com/98112470/306036072-e4313c47-1bd2-457d-8fed-3448ed9feb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjQ4NzIsIm5iZiI6MTcwODM2NDU3MiwicGF0aCI6Ii85ODExMjQ3MC8zMDYwMzYwNzItZTQzMTNjNDctMWJkMi00NTdkLThmZWQtMzQ0OGVkOWZlYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODUyNGQ5MGViYTQ3NDVhZmI5OWEyZTE1NTM5ZmIwN2JiNWVkMmFiNDdjZjYxY2RmNjc5Y2UwMjc1ODQ4ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Q9JnbW6P1wkG5MPi24bVmPtNSiMaH4FlG-53lw4Gk4)
> 
> space.hx line 71:- ![image](https://private-user-images.githubusercontent.com/98112470/306035782-3dd95e0f-da62-403a-8f12-bd7022cf7d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjQ4NzIsIm5iZiI6MTcwODM2NDU3MiwicGF0aCI6Ii85ODExMjQ3MC8zMDYwMzU3ODItM2RkOTVlMGYtZGE2Mi00MDNhLThmMTItYmQ3MDIyY2Y3ZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNTYwZWU0OGFiYzA0NGI0OTZjMWEyZjRiNGIzMzliOTY0YmFjZWM1ODMxNzE5M2ZkNDc0MmFmNjYxMTVjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0-IEhHBscQp7q4f4ET7OmXS5T6pX0T1C3jDaO-18xc) controls.hx line 29:- ![image](https://private-user-images.githubusercontent.com/98112470/306036193-badc7f52-7a1a-4148-821b-2f869d051a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjQ4NzIsIm5iZiI6MTcwODM2NDU3MiwicGF0aCI6Ii85ODExMjQ3MC8zMDYwMzYxOTMtYmFkYzdmNTItN2ExYS00MTQ4LTgyMWItMmY4NjlkMDUxYTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE3NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Mzk4YWVhYTAwZGY0MzljYTk1N2E5ZmIyNmU3N2MzMmRlZGU4ZjA4YTk1ZWVhNTk3ZDA1YzFiYjE3NjIyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jsm6hpTHMiBUX2i49s_MctE8Y-I_IjtjLNNAAQZHh7I)

Yeah, just based on this. I dunno, try it!

**Comment by marioboi3112** [comment]
It gave me an error where `private static function update` was but i removed the static now it works, can you please explain why that fixed the code? i like to learn as i attend game jams! (i'm talking about why the Dynamic type seems to fix the code...)

**Comment by TerryCavanagh** [comment]
Sure - I'm no expert on this stuff, but broadly, if you don't specify a type, haxe will guess, and some situations, it will guess wrong - e.g. it guessed that the variable was going to be of type `Class<Credits>`, so when it was actually of type `Class<Space>` it throws an error. Dynamic is a generic object type that will just work in all situations like this.

The Haxe documentation suggests limiting the use of Dynamic for various technical reasons (https://haxe.org/manual/types-dynamic.html), but to be honest, in practice it's basically fine to just use Dynamic everywhere.

Probably don't follow my programming advice though, I'm kinda infamous for being bad at this ¯\_(ツ)_/¯

**Comment by marioboi3112** [comment]
Thanks terry i will defo check them out! thanks again, have a nice one :)
